name: go-test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  go-test:
    name: go-test
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: go-test
        run: go test ./...
